### ISSUE TITLE
tests pass when run from menu, fail when part of maven install

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#51] opened 2016-03-16 20:58 UTC
After fetching updates I had so may errors thatf I didn't know where to start. So I ran a clean install with Eclipse Installer, which ran the tests under maven. Lots of tests failed. Looking into that, and doing a run as maven install on the project com.ge.research.sadl.tests I get a lot of errors (see below). However, if I run, for example, SadlModelManagerProviderTest manually by right-clicking on the file and choosing run as JUnit test, I get no errors. I suspect that the implementation of ResourceManager.getProjectUri doesn't work when running from maven?

Tests in error: 
  SadlModelManagerProviderTest.mySubClassDeclarationCase:665->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myClassWithPropertyDeclarationCase:401->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myNecesaryAndSufficientCase1:1478->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myNecesaryAndSufficientCase2:1552->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myNecesaryAndSufficientCase3:1626->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myNecesaryAndSufficientCase4:1682->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myIntersectionSuperClassClassDeclarationCase:897->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySimpleClassDeclarationCase:296->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myUserDefinedDatatypeUse1Case:999->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myAnnotationPropertyDeclarationCase:1755->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySimpleClassAsQnDeclarationCase:345->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySimplePropertyDeclarationCase:1033->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.RuleTest1:1879->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myUnionSuperClassWithRestrictionClassDeclarationCase:822->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myClassWith50PropertiesCase:625->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.testDuplicateAliases:145->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myDisjointClassDeclarationCase1:1177->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myDisjointClassDeclarationCase2:1211->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.modelNameCase2:239->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.testDuplicateUris:109->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySameAsComplimentOfCase:1249->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myUnionSuperClassClassDeclarationCase:740->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myPropertyWithListDeclarationCase:1068->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myUserDefinedDatatypeDeclarationCase:956->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySubPropertyDeclarationCase:1143->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myBoxesInstanceCase:1851->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySimpleInstanceDeclarationCase:1718->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.mySameAsCase1:1292->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myNotSameAsCase1:1352->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myNotSameAsCase2:1423->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.myPropertyWithListsDeclarationCase:1103->assertValidatesTo:1945 » NullPointer
  SadlModelManagerProviderTest.modelNameCase:193->assertValidatesTo:1945 » NullPointer

modelNameCase(com.ge.research.sadl.tests.model.SadlModelManagerProviderTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.ge.research.sadl.utils.ResourceManager.getProjectUri(ResourceManager.java:115)
	at com.ge.research.sadl.jena.UtilsForJena.getPolicyFilename(UtilsForJena.java:973)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:236)
	at com.ge.research.sadl.tests.model.SadlModelManagerProviderTest.assertValidatesTo(SadlModelManagerProviderTest.java:1945)
	at com.ge.research.sadl.tests.model.SadlModelManagerProviderTest.modelNameCase(SadlModelManagerProviderTest.java:193)

**Comment by dhuebner** [comment] 2016-03-31 11:44
Is that still an issue? I can't reproduce it.

**Comment by svenefftinge** [comment] 2016-05-03 12:12
closing this as the maven build seem to work now.

**Closed by svenefftinge** 2016-05-03 12:12 UTC
