### ISSUE TITLE
Add proper `hashCode` to `TypeCheckInfo`

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#164] opened 2017-03-28 13:21 UTC
This class has an overridden `equals` but not the `hashCode` which code lead to odd behavior. Implement it + verify with tests.

**Comment by kittaakos** [comment] 2017-03-28 14:11
PR: https://github.com/crapo/sadlos2/pull/165

**Comment by crapo** [comment] 2017-04-03 19:39
I merged this is so I believe the issue is closed. Thanks!

**Closed by crapo** 2017-04-03 19:39 UTC
