### ISSUE TITLE
Bogus code in MetricsProcessor, getModelFolderPath

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#265] opened 2017-10-18 20:47 UTC
@kittaakos , I am seeing a error on SadlColoringTest,, checkColoring_03. I guess MyModel.sadl is supposed to be generated by the test case, and the JenaBasedSadlModelProcessor is called for such a resource, URI being "git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/test-data/test-project/MyModel.sadl". Since this isn't a synthetic URI, a MetricsProcessor is created for the resource and eventually we end up in MetricsProcesor, getModelFolderPath. The code at the top trims all but two segments, leaving for me URI v = "file:///C:/Users/200005201/OwlModels".

I'm not sure how that would work if "v.isPlotform()" returned true, but it doesn't for this test. However, the call to JenaBasedSadlModelProcessor.findModelFolder(resource.getUIR()) returns null, so the "modelFolderPathname" is set to "v.toFileString()", and so later when an attempt is made to write metrics for this resource the error "java.io.FileNotFoundException: C:\Users\200005201\OwlModels\MyModel.sadl.metrics.owl (The system cannot find the path specified)" is generated.

I was cleaning up errors in test cases. Even though they all passed there were a number of errors shown in the console. This is the last one.
And oh, the reason modelFolderPathname comes back null is because by this point the resource is not on the disk apparently.

**Comment by kittaakos** [comment] 2017-10-19 06:30
We either leave with this or disable the tests. As far as I know, we could support `synthetic` URI's with Xtext 2.12. Duplicate of #241. I am merging your findings to the other issue, and I am closing this ticket know.

**Closed by kittaakos** 2017-10-19 06:30 UTC
