### ISSUE TITLE
Copy Qualified Name

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#134] opened 2016-12-13 20:10 UTC
In a SADL model, selecting a concept, right-clicking, and picking Copy Qualified Name returns <baseUri>:<localFragment>, not <baseUri>#<localFragment>. This seems at odds with W3C recommendations....

**Comment by kittaakos** [comment] 2016-12-15 14:37
We will rename the `Copy Qualified Name` to `Copy URI` on the UI and will update the logic to use `#` as the separator before the local name instead of the `:`.

**Comment by kittaakos** [comment] 2016-12-16 12:58
Let assume we have the following resources:
```
uri "http://sadl.org/Shapes.sadl" alias Shapes.

Shape is a class described by area with values of type float.
```

and 
```
uri "http://sadl.org/Circle.sadl" alias Circle.

import "http://sadl.org/Shapes.sadl".

Circle is a type of Shape described by radius with values of type float.
AnotherCircle is a type of Shape described by radius with values of type float.
```

If we copy the `Qualified Name` (which will be renamed to `URI` in the scope of the task) of `Shape`, `Circle` and `AnotherCircle` from the second resource we expect the following URIs:

```
http://sadl.org/Shapes.sadl#Shape
http://sadl.org/Circle.sadl#Circle
http://sadl.org/Circle.sadl#AnotherCircle
```

But what is the expectation if one copies the `radius` from both the `Circle` definition and from the `AnotherCircle` definition?
Currently, both provides `http://sadl.org/Circle.sadl:radius`. (Which will be of course `http://sadl.org/Circle.sadl#radius` once we have fixed and closed this issue.) Does that correct? Although I am not a domain expert, and `Circle` and `AnotherCircle` seem to be redundant anyway, I miss the clear separation between the two `radius` properties.

**Comment by crapo** [comment] 2016-12-16 13:04
There is only one “radius” concept in your example, “http://sadl.org/Circle.sadl#radius”. The domain of this property will, in your example, be the union class of Circle and AnotherCircle. The range will be float. In other words there is no separation, there is only one radius property.

Regards,
Andy

**Comment by kittaakos** [comment] 2016-12-16 13:13
Thank you for the quick reply! Then the copied URI for the `radius` will be `http://sadl.org/Circle.sadl#radius`.

**Comment by crapo** [comment] 2016-12-16 16:21
right

**Comment by kittaakos** [comment] 2016-12-19 16:26
PR for the issue is at: https://github.com/crapo/sadlos2/pull/135

**Comment by crapo** [comment] 2016-12-20 19:36
I can't get the sadl.ui tests associated with this to pass. http://sadl.org/Ontology.sadl#SYSTEM. The fix sees to work well in the IDE.

**Comment by kittaakos** [comment] 2016-12-20 20:00
This test requires a running `org.eclipse.core.runtime.Platform` (with the UI). You have to `Run As > JUnit Plug-in Test`.

**Comment by kittaakos** [comment] 2016-12-21 08:14
Changes merged to master. I close this issue now.
@crapo, please reopen this ticket if you have any problems executing the test in the Eclipse IDE.

**Closed by kittaakos** 2016-12-21 08:14 UTC

**Comment by crapo** [comment] 2016-12-21 22:12
Running as JUnit Plug-in Test fails because it says that I don't have write permission on the .../junit-workspace" folder, which is marked read-only. When I try to change that I get permission denied, even though I'm admin. So rebooting my machine might solve this--it's Windows after all so who could predict? But even if I get this to work as a manual test, what will prevent it from failing as part of the build process initiated from the .launch file?

**Comment by crapo** [comment] 2016-12-22 13:57
Works on my Linux machine. I will also test on Windows.
