### ISSUE TITLE
Declarations not right for variables in query

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#209] opened 2017-06-29 14:30 UTC
[ExpandedProperties.zip](https://github.com/crapo/sadlos2/files/1112347/ExpandedProperties.zip)

In file TestExpandedInQuery.sadl, several things come to light.
If lines 16 and 17 are commented out, line 18 has no errors and p declaration is correct.
If line 17 is uncommented, the declaration of p in line 18 is thought to be in the first occurrence of p in that statement, showing that scoping is not to the single statement. The same issue is illustrated by "po" in lines 13-15.

**Comment by kittaakos** [comment] 2017-06-30 07:59
@crapo please note, there is nothing in the file but empty lines after line 16.

First, I need to verify whether the problem is related to query statement related scoping modification (9b0d215ff4b1d4bf2d5560587a5e650dbc868d2c) or not.

**Comment by kittaakos** [comment] 2017-06-30 08:23
A simplified example:
```
uri "http://sadl.org/foo.sadl".

PhysicalObject is a class described by weight with values of type UnittedQuantity.

Ask: select po where po has weight.
Ask: select po, w where po has weight w.
```

Here, `po` in the second ask resolves to the `po` in the first ask.

**Comment by kittaakos** [comment] 2017-06-30 08:32
This is broken as well:
```
uri "http://sadl.org/bar.sadl".
C is a class.
Ask: select c where c is a C.
```

One can fix it by adding a name to the query. For instance; `Ask ccc: select c where c is a C.` works.

**Comment by crapo** [comment] 2017-06-30 12:08
It should work with or without a query name. Name is optional.

**Comment by crapo** [comment] 2017-06-30 12:10
here's the complete content:
 PhysicalObject is a class described by weight with values of type UnittedQuantity.
 
 MonaLisa is a PhysicalObject with weight 25 lbs.
 AngelOak is a PhysicalObject with weight 10000 lbs.
 
 Ask: weight.
 Ask: weight of x.
 Ask: x has weight.
 Ask: weight of AngelOak.
 Ask: AngelOak has weight.
 Ask: select po where po has weight. 
 Ask: select po, w where po has weight w. 
 Ask: select po, v, u where po has weight w and w has ^value v and w has unit u. 
 Ask: select po, v, u where po has weight w and w has ^value v and w has unit u and v > 1000 .  
 Ask: select p where p is a PhysicalObject.
 Ask Named: select p where p is a PhysicalObject.

**Comment by crapo** [comment] 2017-06-30 21:28
I have generalized named structures and updated SadlImplicitModel to have classes for those named structures. I have pushed the corresponding Requirements repo. I've added two test cases. One is SadlLinkingTest.testQueryVariable_1. It has the failing queries commented out in the model, and so directly tests this issue. The other test is SadlModelProcessorTestBasics.testNamedStructureAnnotationsRule and it has a query in the model commented out because it fails because the class in the SadlImplicitModel is apparently not being loaded. Did I forget how to get the implicit model loaded in a test case?

**Comment by svenefftinge** [comment] 2017-07-18 11:26
Akos and I discussed it today. To make sure we are all on the same page. This is how I think it should link, using our test syntax ([]=definition, <>=reference):

```
[PhysicalObject] is a class described by [weight] with values of type UnittedQuantity.

[MonaLisa] is a <PhysicalObject> with <weight> 25 lbs.
[AngelOak] is a <PhysicalObject> with <weight> 10000 lbs.

Ask: <weight>.
Ask: <weight> of [x].
Ask: [x] has <weight>.
Ask: <weight> of <AngelOak>.
Ask: <AngelOak> has <weight>.
Ask: select [po] where <po> has <weight>.
Ask: select [po], [w] where <po> has <weight> <w>.
Ask: select [po], [v], [u] where <po> has <weight> [w] and <w> has ^value <v> and <w> has unit <u>.
Ask: select [po], [v], [u] where <po> has <weight> [w] and <w> has ^value <v> and <w> has unit <u> and <v> > 1000 .
Ask: select [p] where <p> is a <PhysicalObject>.
Ask Named: select [p] where <p> is a <PhysicalObject>.
```
That is, the variables coming right after the `select` keyword are local variable definitions. Also I think statements made within `Ask:` should not be visible at all outside, so neither explicit variable declarations (after `select`) nor implicit ones from expressions should leave the scope of an `Ask:` statement.

**Comment by crapo** [comment] 2017-07-20 11:49
Scope is correct--variables should not leave the scope of the Ask statement.
However, variable definition in an Ask: select... statement is not in the variables named after the select (before the where) but rather in the first occurrence in the where clause itself. The variables after select just indicate which variables should be returned in the tabular results.
Consider these examples:
**Ask: [x] has <weight> [y].**     // here it is clear where the definition of x and y occur.
**Ask: select <x>, <y> where [x] has <weight> [y].**  // adding the select doesn't change where vars are defined. The definitions are where we can identify types (domain, range of <weight>)
**Ask: select * where [x] has <weight> [y].**     // this means include all variables in results; definition locations unchanged

**Comment by kittaakos** [comment] 2017-08-31 08:55
It was implemented and the corresponding changes can be found on the master. Closing this task.

**Closed by kittaakos** 2017-08-31 08:55 UTC
